[FEAT] add Practice for Closure part1 & part2
42js/you-dont-know-js-yet pull request #15
Opened 2021-01-10 11:42 UTC by pje1740

[Issue]
#14 

[Description]
Closure part1, part2 코드입니다.
factorize 관련해서 궁금한 게, 재귀로 또 가져오는 부분에서 만약 캐시가 그 값을 알고 있다면 그걸 바로 가져오게 했는데 Suggested Solution에는 이런 작업을 별도로 하진 않은 거 같아서 의문이 생겼습니다.
뭔가 잘못 생각했나 싶기도 한데 혹시나 관련해서 조언이 있다면 코멘트 부탁드리겠습니다!

2021-01-10 11:49 UTC, cos18 requested changes
#12 `practice` 폴더가 아닌 `practice_new` 폴더에 만들어주세요!

2021-01-10 12:31 UTC, GwangYeol-Im approved these changes

2021-01-10 12:31 UTC, GwangYeol-Im commented on 2_Scope_Closures/practice/closure_part1_sohpark.js
> +    if (cache.get(v) === undefined) {
첫번째 if 문에서 이미 cache 안에 소수가 있는지 검사하는 것 같은데 해당 조건 분기를 어떤 이유에서 추가하셨는지 궁금합니다 !

2021-01-10 12:31 UTC, GwangYeol-Im commented on 2_Scope_Closures/practice/closure_part1_sohpark.js
> +  var cache = new Map();
cache의 자료구조를 따로 map 으로 설정해주신 이유가 있을까요?

2021-01-10 12:31 UTC, GwangYeol-Im commented on 2_Scope_Closures/practice/closure_part1_sohpark.js
> +})();
재귀 레벨에 따라 각 인자를 등록하는 걸로 알고 있는데 현재 로직 상으로는 오직 소수일 때만 cache에 저장해주니 큰 수에 대한 연산은 조금 늦지 않을까 싶습니다~

2021-01-10 13:23 UTC, YUJO42 approved these changes
코드 잘 봤습니다! 전체적으로 깔끔해서 보기 좋은 코드였네요👍👍👍

2021-01-10 13:23 UTC, YUJO42 commented on 2_Scope_Closures/practice/closure_part2_sohpark.js
> +function toggle() {
```suggestion
function toggle(...arguments) {
```

저도 다른 분들 PR보다가 알게 됐는데 이렇게 스프레드 연산자를 사용해서 ```arguments```를 받아오면 함수 내부에서 새로운 변수를 선언할 필요가 없어서 좋더라구요!

2021-01-10 13:23 UTC, YUJO42 commented on 2_Scope_Closures/practice/closure_part2_sohpark.js
> +  let args = arguments;
혹시 이 부분에서 ```count```는 값을 조작하기 떄문에 ```var```를 사용하신건가요? ```args```는 ```let```으로 선언하셔서 이유가 궁금합니다!

2021-01-10 14:05 UTC, dawnbeen approved these changes
제가 궁금한 부분들을 이미 다른 분들이 질문해주셔서 ㅋㅋㅋ 따로 다른 리뷰 남기지 않았는데 코드 잘 봤습니다!! 😃   전체적으로 깔끔한 것 같아요 ㅎㅎ

2021-01-10 23:36 UTC, pje1740 commented on 2_Scope_Closures/practice/closure_part1_sohpark.js
> +})();
으어닛 해놓고 보니 그렇네요...! 아침에 맑은 정신으로 다시 봐야겠습니닼ㅋㅋㅋㅋ

2021-01-10 23:38 UTC, pje1740 commented on 2_Scope_Closures/practice/closure_part1_sohpark.js
> +  var cache = new Map();
그냥 오브젝트면 정확하진 않지만 캐시된 자료를 찾을 때 시간 복잡도가 올라가지 않을까 해서 기왕 Map이 있으니 캐시 검색의 시간을 줄이려는 목적으로 Map을 썼습니다!

2021-01-10 23:43 UTC, pje1740 commented on 2_Scope_Closures/practice/closure_part1_sohpark.js
> +    if (cache.get(v) === undefined) {
위에서 모든 조건을 체크하고도 캐시에 등록되지 않으면 소수이기 때문에 그 부분을 적어준 내용이긴합니다. 소수가 아니었다면 등록을 했을 거라 한번 더 체크해서 피할 필요가 있었네요...! 사실 내부에서 그냥 return 처리를 다 해줘도 됐을 텐데 쓰다보니 최종적인 return은 딱 한번만 하고 싶어서 이런 요상한 코드가 나온 거 같네요! ㅎㅎㅎ;;;

2021-01-10 23:52 UTC, pje1740 commented on 2_Scope_Closures/practice/closure_part2_sohpark.js
> +  let args = arguments;
습관성 let이네요... 지적 감사합니다!

2021-01-11 00:02 UTC, pje1740 commented on 2_Scope_Closures/practice/closure_part1_sohpark.js
> +  var cache = new Map();
https://medium.com/@wdjty326/javascript-es6-map-vs-object-performance-%EB%B9%84%EA%B5%90-7f98e30bf6c8
좀 더 찾아보니 자료를 get 할 일이 많으면 Map, set할 일이 더 많으면 객체가 유리하다고 하네요! 아무래도 캐시 특성상 get을 해올 일이 많아질 거 같기도 해서 Map으로 해도 큰 탈은 없을 거라고 생각은 됩니다! 다만 저자가 Map같은 자료구조를 쓰는 걸 썩 좋아하시는지는 모르겠습니다ㅎㅎㅎ

2021-01-11 00:41 UTC, GwangYeol-Im commented on 2_Scope_Closures/practice/closure_part1_sohpark.js
> +  var cache = new Map();
아하.. 그런 측면에서도 생각해볼 수 있겠네요 나중에 이 부분은 개인적으로 공부해보겠습니다 ㅎㅎ

2021-01-11 00:41 UTC, GwangYeol-Im commented on 2_Scope_Closures/practice/closure_part1_sohpark.js
> +    if (cache.get(v) === undefined) {
아아 그러네요 ㅋㅋㅋㅋ 아닙니다 제가 이해를 잘못 했었네요!

2021-01-11 08:01 UTC, merged